default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: railsdb

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: <%= ENV['PGDATABASE'] %>

test:
  <<: *default
  database: railsdb_test
