default: &default
  adapter: postgresql
  encoding: unicode
  host: railsdb
  username: postgres
  password: P@55w0rd
  pool: 5

development:
  <<: *default
  database: railsdb

production:
  <<: *default
  database: railsdb


test:
  <<: *default
  database: railsdb_test
